spring:
  profiles:
    active: db, core, admin
  message:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall:  ERROR