package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserCredit;
import org.linlinjava.litemall.db.domain.LitemallUserCreditExample;

public interface LitemallUserCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int insert(LitemallUserCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserCredit selectOneByExample(LitemallUserCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserCredit selectOneByExampleSelective(@Param("example") LitemallUserCreditExample example, @Param("selective") LitemallUserCredit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallUserCredit> selectByExampleSelective(@Param("example") LitemallUserCreditExample example, @Param("selective") LitemallUserCredit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    List<LitemallUserCredit> selectByExample(LitemallUserCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserCredit selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserCredit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    LitemallUserCredit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserCredit record, @Param("example") LitemallUserCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserCredit record, @Param("example") LitemallUserCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserCredit record);
}